server:
  port: 9090

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.89.188:3306/flowable_test?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    #type: com.alibaba.druid.pool.DruidDataSource

#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

  thymeleaf:
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html

flowable:
  common:
    app:
      idm-url: http://127.0.0.1:9090/flowable-idm

#mybatis:
#  mapper-locations: classpath:mapper/*.xml